[functions.queue-analyze]
entrypoint = "./functions/queue-analyze/index.js"

[functions.process-analyze]
entrypoint = "./functions/process-analyze/index.js"

[functions.check-status]
entrypoint = "./functions/check-status/index.js"

[functions.batch-analyze]
entrypoint = "./functions/batch-analyze/index.js"

[functions.get-pdf-base64]
entrypoint = "./functions/get-pdf-base64/index.js"