
[functions.queue-analyze]
entrypoint = "./functions/queue-analyze/index.js"

[functions.process-analyze]
entrypoint = "./functions/process-analyze/index.js"

[functions.check-status]
entrypoint = "./functions/check-status/index.js"
